const img_loc_pub = 'http://localhost:3000/src/assets/images/1.png'
// const img_loc_pub = 'https://rayweblistapi.000webhostapp.com/assets/Afari_achat.c86baf17.png'

export let rent_objects = [
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    }
]